{{- if and .Values.wordpress.persistence.enabled (not .Values.wordpress.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-data
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size | quote }}
  {{- if .Values.wordpress.persistence.storageClass }}
  {{- if (eq "-" .Values.wordpress.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}-data
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}
  {{- if .Values.mysql.persistence.storageClass }}
  {{- if (eq "-" .Values.mysql.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
