apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.mysql.secretName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mysql.enabled }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
